# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f2592994d868454fe8a45d5f3aefc7d8fd88d3e8f50ea66226b5c1c08dde6b99376375785b043f9a1517b307fd4ddd87554538a76af777f90ef942e367723e7b
  paypal_email: "syaiful-facilitator@getkeet.com"
  paypal_url: "https://www.sandbox.paypal.com"
  site_url: "https://e6d1377d.ngrok.io"

test:
  secret_key_base: eacd1c3a2d3a78362041008b4976c5664cdd2d72016a653b33eb7bdf35405c489a48ca7d920671d46f0a2480ec29b8ed683a1d325bc0bc7dcb3cdb3140899ae7
  paypal_email: "syaiful-facilitator@getkeet.com"
  paypal_url: "https://www.sandbox.paypal.com"
  site_url: "http://42ebe2d6.ngrok.io"
circleci:
  secret_key_base: eacd1c3a2d3a78362041008b4976c5664cdd2d72016a653b33eb7bdf35405c489a48ca7d920671d46f0a2480ec29b8ed683a1d325bc0bc7dcb3cdb3140899ae7
  paypal_email: "syaiful-facilitator@getkeet.com"
  paypal_url: "https://www.sandbox.paypal.com"
  site_url: "http://42ebe2d6.ngrok.io"

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: 'e19604b29fda5b0a00c770413e804d195cef4f7e8ef701410bfb648c77d57b6007d6d7937f4bbf5df580f1d1141cbb2dd597d2dfe1c7e7df1e51a0b5edbe0c'
  paypal_email: "syaiful@getkeet.com"
  paypal_url: "https://www.paypal.com"
  site_url: "http://42ebe2d6.ngrok.io"